"""``IdeHandoffBackend`` — prepare a grounded task packet for any editor.

This is the backend for people who'd rather drive their editor than an
unattended CLI loop.  It does everything *except* write the code: it grounds the
design up front, then drops a ``TASK.md`` packet at the root of the task's
isolated worktree containing the task, the design slice, the preflight grounding
result, the oracle commands, and a checklist.  You open that worktree folder in
your editor of choice, implement the task (with whatever coding assistant you
use, or none), and run ``harness pipeline complete <task-id>`` — which re-grounds
your changes, runs the review gate, and opens the PR.

It is always available (no external CLI required), which is why it's the default
backend.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from harness.log import get_logger, trunc

from .. import gitutil
from ..sanitize import sanitize_design
from .base import CodingBackend, ImplementContext, ImplementOutcome

logger = get_logger(__name__)

PACKET_NAME = "TASK.md"


class IdeHandoffBackend(CodingBackend):
    name = "ide-handoff"

    def implement(self, ctx: ImplementContext) -> ImplementOutcome:
        task = ctx.task

        # Preflight: ground whatever code the design already proposes, so the
        # packet warns about hallucinated symbols before you write a line.
        logger.debug("preflight-grounding %s: %d chars of %s",
                     task.id, len(ctx.design_text or task.description),
                     "design text" if ctx.design_text
                     else "task description (no design text attached)")
        gate = ctx.gate()
        preflight = gate.check_design(ctx.design_text or task.description)
        logger.debug("preflight grounding for %s: ok=%s, files_checked=%d — %s",
                     task.id, preflight.ok, preflight.files_checked,
                     preflight.summary)

        packet = self._render_packet(ctx, preflight_summary=preflight.summary,
                                     preflight_findings=_findings(preflight))
        packet_path = ctx.worktree / PACKET_NAME
        packet_path.write_text(packet, encoding="utf-8")
        logger.info("task packet written for %s: %s (%d chars, %d oracle "
                    "command(s), preflight %s)",
                    task.id, packet_path, len(packet), len(ctx.validation),
                    preflight.summary)

        # Commit the packet so the worktree has a clean starting point and the
        # branch exists for the eventual PR.
        gitutil.add_all(ctx.worktree)
        commit = gitutil.commit(ctx.worktree, f"chore: task packet for {task.id}")
        if not commit.ok:
            # Fail-open: the packet is still on disk and usable, but the branch
            # may lack the clean start point `pipeline complete` expects.
            logger.warning("packet commit failed for %s (rc=%d) — continuing "
                           "with an uncommitted packet: %s",
                           task.id, commit.code,
                           trunc((commit.err or commit.out or "").strip(), 300))

        ctx.log(f"  ✎ wrote {PACKET_NAME} → {packet_path}")
        ctx.log(f"    open this folder in your editor:  {ctx.worktree}")
        logger.info("%s: → awaiting-human (implement in %s, then run "
                    "`harness pipeline complete %s`)",
                    task.id, ctx.worktree, task.id)
        return ImplementOutcome(
            status="awaiting-human",
            oracle_passed=False,
            grounding_ok=preflight.ok,
            detail=f"task packet ready for IDE implementation ({preflight.summary})",
            packet_path=str(packet_path),
            grounding_summary=preflight.summary,
        )

    # ── packet rendering ──────────────────────────────────────────────────────

    def _render_packet(self, ctx: ImplementContext, *, preflight_summary: str,
                        preflight_findings: str) -> str:
        task = ctx.task
        validation = "\n".join(f"- [ ] `{c}` exits 0" for c in ctx.validation) \
            or "- [ ] (no validation commands configured — add some!)"
        verify_hint = (
            "harness verify <file>.py --project ."
            if ctx.validation else "harness verify <file>.py --project ."
        )
        return f"""# Task packet — {task.title}

> Generated by the harness design-docs → PRs pipeline. Implement this task in
> **this worktree** using your editor of choice, then run the *Complete*
> step to ground, review, and open the PR. Do not hand-edit the metadata below.

| | |
|---|---|
| **Task id** | `{task.id}` |
| **Risk** | `{task.risk}` |
| **Branch** | `{ctx.task.branch or gitutil.current_branch(ctx.worktree)}` |
| **Source design** | `{task.design_doc}` |
| **Worktree** | `{ctx.worktree}` |

## What to build

{sanitize_design(task.description)}

## Definition of done (the oracle)

Your change is complete only when every box is checked:

{validation}
- [ ] Every symbol you reference exists (grounding gate passes)

## Preflight grounding

The pipeline grounded the code already present in the design against this repo +
the installed environment:

> {preflight_summary}
{preflight_findings}
As you write, ground individual files yourself:

```bash
{verify_hint}
```

(Editors that load the harness repo's `.vscode/tasks.json` can run the task
**Harness: Grounding check current file**.)

## When you're done

Commit your work in this worktree, then run:

```bash
harness pipeline complete {task.id} --repo "{ctx.config.repo}"
```

or run the editor task **Harness: Complete task → PR**. That step re-grounds
your changes, runs the validation oracle, assigns a risk level, and opens the
PR (`--pr local` branch or `--pr github`).

---
<!-- harness:task={task.id} -->
"""


def append_feedback_round(worktree: Path | str, feedback: str, *,
                          risk: str = "", summary: str = "") -> int:
    """Append a structured "still failing" round to the worktree's ``TASK.md``.

    This is the harness's loss-free, editor-native human-feedback loop: when
    ``pipeline complete`` finds the IDE-implemented work
    still red, the exact oracle + grounding findings are appended to the packet —
    they accumulate across rounds rather than being lost to a one-line CLI
    "failed", so the next edit pass has the full history to act on. Returns the
    new round number (1-based). A no-op (returns 0) if there's no packet.
    """
    packet = Path(worktree) / PACKET_NAME
    if not packet.is_file():
        # Fail-open: the caller still reports "failed" on the CLI, but the
        # findings won't accumulate in the editor-visible packet.
        logger.warning("no %s in %s — feedback round dropped (still-failing "
                       "findings will not reach the editor packet)",
                       PACKET_NAME, worktree)
        return 0
    existing = packet.read_text(encoding="utf-8")
    # Count a controlled marker we emit (an HTML comment), NOT the visible header
    # text — oracle feedback embedded in a prior round's fenced body can contain
    # the header string verbatim and would otherwise inflate the round number.
    round_no = len(re.findall(r"<!-- harness:review-round \d+ -->", existing)) + 1
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    head = f"\n\n## Review round {round_no} — still failing ({ts})\n<!-- harness:review-round {round_no} -->\n"
    meta = f"\n> risk: `{risk or 'n/a'}`" + (f" — {summary}" if summary else "") + "\n"
    body = feedback.strip() or "(no detail captured)"
    section = f"{head}{meta}\n```\n{body}\n```\n\nFix the above, then re-run the *Complete* step.\n"
    packet.write_text(existing + section, encoding="utf-8")
    logger.info("feedback round %d appended to %s (%d chars of findings, "
                "risk=%s)", round_no, packet, len(body), risk or "n/a")
    return round_no


def _findings(preflight) -> str:
    """Render the failing grounding verdicts from the preflight, if any."""
    if preflight.ok or not preflight.reports:
        return "\n> ✓ no hallucinated symbols found in the design's code blocks.\n"
    lines = ["\n**Hallucinated / unresolved symbols already in the design:**\n"]
    for label, report in preflight.reports.items():
        for v in report.verdicts:
            if v.status in ("ungrounded", "contradicted"):
                tip = f" (did you mean: {', '.join(v.suggestions)}?)" if v.suggestions else ""
                lines.append(f"- `{label}` L{v.lineno} [{v.kind}] {v.message}{tip}")
    lines.append("")
    return "\n".join(lines)
